### ISSUE TITLE
What's the performance when the drone works in unknown env?

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/am_traj#1]
These examples work in global 3D map. Have you tested the performance when the obstruction is local and unknown?

**Comment by ZhepeiWang** [comment]
No, we have not tested it in local planning scenarios systematically. However, we have applied this trajectory generation & feasibility checker module in our on-going work about local planners, which also enable aggressive yet safe flights. However, the performance of the drone flight is determined by a complete planning framework instead of our single module. That's the reason why we only test the functionalities of our module with other similar modules.

As is shown in our example 1, the application of our module, in global planning or in local planning, should involve a high level planner which is able to feed inputs and constraints into our module. Therefore, we hope the efficiency of the module is helpful if you want to use it in a local planning problem.

**Comment by dssdyx** [comment]
@ZhepeiWang I see this video in your lab website about this project. http://www.kivact.com/teach-repeat-replan/. I guess the example in video used this project as global and local planning. Realsense camera provided depth map to help build local and global 3D map. Is it right? It's meant when using i7, there is enough respond time for drone in unknown env to run.

**Comment by USTfgaoaa** [comment]
@dssdyx That's for teach-repeat-replan, not this project.
