### ISSUE TITLE
yaw in am_traj

### ISSUE THREAD

**Issue by mpkuse** [ZJU-FAST-Lab/am_traj#4]
Hi,
I am trying to generate trajectories with am_traj. Thanks for sharing your code. 

My issue is that, instead of XYZ-trajectory I want to have XYZ,Yaw-trajectory. Is this kind of thing
simply possible with AM-traj. 

In my mind I am thinking to implement the following: 
- Generate XYZ trajectory.
- Once we know the time allocation from the above trajectory pieces, use this time allocation and generate a spline trajectory for the yaw. 

Do you think such a workaround would work? I am looking for your suggestion.

Thank!

**Comment by ZhepeiWang** [comment]
Roughly speaking, such a workaround will work, but not perfectly. 


There are two main reasons. First, yaw trajectory requires optimization on SO(2) instead of R. Otherwise, weird turning occurs when a major arc is predetermined by a trajectory on R. Second, trajectory optimization on a group needs a more flexible optimization framework such that the gradient on a group can be explicitly defined. This is obviously not supported by this repo which is not a gradient-based solver. Actually, this repo is deprecated due to its lack of flexibility.

For multicopter trajectory planning, the new repo GCOPTER is recommended (https://github.com/ZJU-FAST-Lab/GCOPTER). The methodology in this new repo supports almost any constraint which is convenient for optimization on SO(2). Unfortunately, according to our plan, it has not been open-sourced yet. Thus I think I will give a better yaw optimization scheme when this new repo is released.
