### ISSUE TITLE
Apply the control command for the drone in simulation with px4 and mavros

### ISSUE THREAD

**Issue by chenhanpolyu** [ZJU-FAST-Lab/am_traj#5]
Hi, I am impressed by your work about computing efficiency and fast flight speed and have no BUG to report. Thanks for your open-source code. I hope to test your method with my drone with a pixhawk flight controller. However, in your project, I found that the ROS topic conveyed to the simulated drone seems to contain position, velocity and acceleration commands at the same time. For Px4 offboard mode, I think only one command type is allowed to be executed at the time. Is there any solution to translate your ROS topic to control a Px4 drone?
 
I thought /drone_1/position_cmd and /drone_1/so3_command may be the desired value to pass to the flight controller, I am not sure if am I right?

**Comment by ZhepeiWang** [comment]
We use position, velocity ,acceleration, and even jerk in our real-world trajectory tracking controller. For details, we refer to (https://arxiv.org/abs/1712.02402) and its attached controller code. However, this repo is deprecated and no-longer maintained due to its inflexibility.

It is encouraged to use **EGO**-planner (https://github.com/ZJU-FAST-Lab/ego-planner) for real-flight local planner where **the code for p,v,a tracking controller is provided for N3**, or wait for **GCOPTER** (https://github.com/ZJU-FAST-Lab/GCOPTER) for real-time full-state global/local planning with almost full-state tracking control for PX4.

**Comment by chenhanpolyu** [comment]
Thank you for your detailed reply, I will go through the paper you mentioned. Can ego-planner apply on a real drone with a PX4 flight controller? The page (https://github.com/ZJU-FAST-Lab/ego-planner) doesn't mention this. To be honest, I am not very familiar with PX4, I will very much appreciate your help if you know how to enable the PX4 controller following the trajectory output by am_traj. 
Another question is, is the method in am_traj also applied in ego-planner?

**Comment by ZhepeiWang** [comment]
Actually, there is no open-sourced repo of ours supporting PX4 controller. All these repos only support DJI N3 controller. If you use PX4, it is suggested to use MAVROS for thrust and angular rate control, then an upper-level controller ROS node should be running in onboard computer for p, v, a, and j computing and tracking. The upper-level controller takes the trajectory of planner as its inputs. It outputs thrust and angular rate for PX4 through MAVROS Node and TTL2USB Module. 

Of course, you can also modify our controller for N3 but it only support outputing thrust and tilting angle instead of angular rate, but PX4 definitely supports tilting angle. By the way, I forgot to mention that the controller for N3 in EGO is from Teach-Repeat-Replan (https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/experiment/onboard_computer/controller).

As for the second question, am_traj is only a waypoint-based planner, suffering the inner inflexibility of all waypoint-based ones. Thus it is not used in EGO-Planner.

**Comment by chenhanpolyu** [comment]
Thanks for your clear explaination! I will try following your suggestion. 
Wish you all the best.
